# GET http://localhost:5501/get-all-interest

# POST http://localhost:5501/upload-interest
# Content-Type: application/json

# {
#     "user_name": "abc",
#     "question_one_ans": "test2",
#     "question_two_ans": "test2",
#     "question_three_ans": "test2",
#     "question_four_ans": "test2",
#     "question_five_ans": "test2"
# }

GET http://localhost:5501/get-interest/yeetao